create table users
(
    id uuid not null primary key,
    first_name varchar(255) not null,
    last_name  varchar(255) not null,
    email      varchar(255) not null unique,
    phone      varchar(255) not null unique,
    cpf        varchar(255) not null unique,
    created_at timestamp(6) not null
);

create table addresses
(
    id uuid not null primary key,
    street       varchar(255) not null,
    number       varchar(255),
    complement   varchar(255),
    neighborhood varchar(255) not null,
    city         varchar(255) not null,
    state        varchar(255) not null,
    cep          varchar(255) not null,
    user_id uuid not null references users
);

create table brands
(
    id         bigint generated by default as identity primary key,
    brand_name varchar(255) not null unique
);

create table categories
(
    id            bigint generated by default as identity primary key,
    category_name varchar(255) not null unique
);

create table colors
(
    id         bigint generated by default as identity primary key,
    color_name varchar(255) not null unique
);

create table sizes
(
    id          bigint generated by default as identity primary key,
    size_name   varchar(255) not null,
    category_id bigint       not null references categories
);

create table products
(
    id uuid not null primary key,
    name        varchar(255)   not null,
    price       numeric(38, 2) not null,
    description varchar(255)   not null,
    size_id     bigint         not null references sizes,
    brand_id    bigint         not null references brands,
    color_id    bigint         not null references colors,
    category_id bigint         not null references categories,
    created_at  timestamp(6)   not null
);